[package]
name = "amf_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.64.0"
windows-bindgen = "0.44.0"
cc = "1.0.79"

[dependencies]
cc = "1.0.79"
libloading = "0.7.4"
