#include <stdio.h>
#include <tchar.h>
#include <d3d9.h>
#include <d3d11.h>
#include <process.h>
#include <windows.h>
#include "./AMF/amf/public/include/core/Factory.h"
#include "./AMF/amf/public/include/core/Version.h"
#include "./AMF/amf/public/include/components/VideoEncoderVCE.h"
